version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "proxy"
    depends_on:
      - "proxy"
    networks:
      - "default"
      - "proxy-tier"

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.fintechsys.net
      - LETSENCRYPT_HOST=portainer.fintechsys.net
      - LETSENCRYPT_EMAIL=m.nozili@fintechsys.net
      - VIRTUAL_PORT=9000
    volumes:
      - ./portainer/:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
 
  postgresql:
    image: postgres:11.8
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - postgresql-vol:/var/lib/postgresql/data

  redis-cache:
    container_name: redis-cache
    restart: unless-stopped
    image: redis:alpine

  redis-queue:
    container_name: redis-queue
    restart: unless-stopped
    image: redis:alpine

  redis-socketio:
    container_name: redis-socketio
    restart: unless-stopped
    image: redis:alpine

  frappe:
    container_name: switch
    restart: unless-stopped
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
      - VIRTUAL_HOST=frappe.fintechsys.net
      - LETSENCRYPT_HOST=frappe.fintechsys.net
      - LETSENCRYPT_EMAIL=m.nozili@fintechsys.net
      - VIRTUAL_PORT=8000
      
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/development
  
  frappe-switch:
    container_name: switch
    restart: unless-stopped
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
      - VIRTUAL_HOST=switch.fintechsys.net
      - LETSENCRYPT_HOST=switch.fintechsys.net
      - LETSENCRYPT_EMAIL=m.nozili@fintechsys.net
      - VIRTUAL_PORT=8000
      
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/development
  




volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:



